### ISSUE TITLE
NotImplementedError: only the default get_loc method is currently supported for MultiIndex

### ISSUE THREAD

**Issue by leolle** [cvxgrp/cvxportfolio#3] opened 2017-08-03 06:47 UTC
I have this error when I run the HelloWorld example.
Can anybody tell me how to fix it? Thank you.

```
market_sim=cp.MarketSimulator(returns, [tcost_model, hcost_model], cash_key='USDOLLAR') 
init_portfolio = pd.Series(index=returns.columns, data=0.)
init_portfolio.USDOLLAR = 100
result = market_sim.run_backtest(init_portfolio,
                               start_time='2013-01-03',  end_time='2016-12-31',  
                               policy=spo_policy)

result.summary()
--------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-9-b229f1c1f6b4> in <module>()
      4 result = market_sim.run_backtest(init_portfolio,
      5                                start_time='2013-01-03',  end_time='2016-12-31',
----> 6                                policy=spo_policy)
      7 
      8 result.summary()

/home/weiwu/projects/cvxportfolio/cvxportfolio/simulator.py in run_backtest(self, initial_portfolio, start_time, end_time, policy, loglevel)
    114             start = time.time()
    115             try:
--> 116                 u = policy.get_trades(h, t)
    117             except cvx.SolverError:
    118                 logging.warning(

/home/weiwu/projects/cvxportfolio/cvxportfolio/policies.py in get_trades(self, portfolio, t)
    222 
    223         for cost in self.costs:
--> 224             cost_expr, const_expr = cost.weight_expr(t, wplus, z, value)
    225             costs.append(cost_expr)
    226             constraints += const_expr

/home/weiwu/projects/cvxportfolio/cvxportfolio/risks.py in weight_expr(self, t, w_plus, z, value)
     43 
     44     def weight_expr(self, t, w_plus, z, value):
---> 45         self.expression = self._estimate(t, w_plus - self.w_bench, z, value)
     46         return self.gamma * self.expression, []
     47 

/home/weiwu/projects/cvxportfolio/cvxportfolio/risks.py in _estimate(self, t, wplus, z, value)
     81     def _estimate(self, t, wplus, z, value):
     82         try:
---> 83             self.expression = cvx.quad_form(wplus, locator(self.Sigma, t))
     84         except TypeError:
     85             self.expression = cvx.quad_form(

/home/weiwu/projects/cvxportfolio/cvxportfolio/risks.py in locator(obj, t)
     30     """Picks last element before t."""
     31     try:
---> 32         return obj.iloc[obj.axes[0].get_loc(t, method='pad')]
     33     except AttributeError:  # obj not pandas
     34         return obj

/home/weiwu/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/pandas/core/indexes/multi.py in get_loc(self, key, method)
   1946         """
   1947         if method is not None:
-> 1948             raise NotImplementedError('only the default get_loc method is '
   1949                                       'currently supported for MultiIndex')
   1950 

NotImplementedError: only the default get_loc method is currently supported for MultiIndex
```

**Comment by jonathanng** [comment] 2017-08-03 14:22
I fixed this issue on my branch. I've already made a pull request, but there has been no response. You can download my fixed version here:

https://github.com/jonathanng/cvxportfolio

**Comment by leolle** [comment] 2017-08-04 02:16
@jonathanng 
thank you, I cloned your branch, but new error came up.
I am using anaconda3-4.4.0.
```
/home/weiwu/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/cvxpy/atoms/quad_form.py:81: UserWarning: Forming a nonconvex expression quad_form(x, indefinite).
  warnings.warn("Forming a nonconvex expression quad_form(x, indefinite).")

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-8-b229f1c1f6b4> in <module>()
      4 result = market_sim.run_backtest(init_portfolio,
      5                                start_time='2013-01-03',  end_time='2016-12-31',
----> 6                                policy=spo_policy)
      7 
      8 result.summary()

/home/weiwu/projects/cvxportfolio/cvxportfolio/simulator.py in run_backtest(self, initial_portfolio, start_time, end_time, policy, loglevel)
    114             start = time.time()
    115             try:
--> 116                 u = policy.get_trades(h, t)
    117             except cvx.SolverError:
    118                 logging.warning(

/home/weiwu/projects/cvxportfolio/cvxportfolio/policies.py in get_trades(self, portfolio, t)
    236 
    237         for el in costs:
--> 238             assert (el.is_convex())
    239 
    240         for el in constraints:

AssertionError: 


```

**Comment by jonathanng** [comment] 2017-08-04 14:33
Try updating your copy of cvxopt:

`pip install cvxopt -U`

Also in my branch, I cleaned up the HelloWorld example code. Try to see if that works.

**Comment by leolle** [comment] 2017-08-08 09:11
@jonathanng 
My cvxopt versions is up to date.
Here's another error:
```
home/weiwu/.pyenv/versions/anaconda3-4.4.0/lib/python3.6/site-packages/cvxpy/atoms/quad_form.py:81: UserWarning: Forming a nonconvex expression quad_form(x, indefinite).
  warnings.warn("Forming a nonconvex expression quad_form(x, indefinite).")

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-7-22d34144d184> in <module>()
     12     start_time        = '2013-01-03',
     13     end_time          = '2016-12-31',
---> 14     policy            = spo_policy
     15 )
     16 

/home/weiwu/projects/tmp/test/cvxportfolio/cvxportfolio/simulator.py in run_backtest(self, initial_portfolio, start_time, end_time, policy, loglevel)
    114             start = time.time()
    115             try:
--> 116                 u = policy.get_trades(h, t)
    117             except cvx.SolverError:
    118                 logging.warning(

/home/weiwu/projects/tmp/test/cvxportfolio/cvxportfolio/policies.py in get_trades(self, portfolio, t)
    236 
    237         for el in costs:
--> 238             assert (el.is_convex())
    239 
    240         for el in constraints:

AssertionError: 


```

**Comment by jonathanng** [comment] 2017-08-08 13:32
Which notebook is this? HelloWorld?

**Comment by leolle** [comment] 2017-08-09 02:37
yes, hello world.
I have no problem with preload data optimization and simulation.

**Comment by jonathanng** [comment] 2017-08-09 19:59
Which cell/line is giving you this error?

**Comment by jonathanng** [comment] 2017-10-12 12:23
I'm not sure what the issue is. It's hard to say without have the same environment. Have you tried a fresh install of Python & cvxportfolio?

**Comment by jonathanng** [comment] 2018-01-24 21:10
I encountered a similar error and I found that if you have negative borrow rates, it won't be able to determine if the problem is convex.

One easy fix would be to do something like:
```python
borrow_costs[borrow_costs < 0.0] = 0.0
```

**Comment by enzobusseti** [comment] 2018-04-23 21:28
This should be fixed now.

**Closed by enzobusseti** 2018-04-23 21:28 UTC

**Comment by kenuku** [comment] 2020-05-23 06:44
You need to sort the columns alphabetically in 'returns' DataFrame. 
Probably 'cvxpy' not fully compatible with pandas.
I spent three days searching for this glitch

**Comment by kenuku** [comment] 2020-05-24 05:54
And the cash asset should be in last place, i.e. in the last column as described in paper:

https://web.stanford.edu/~boyd/papers/pdf/cvx_portfolio.pdf

This column can be called '_USDOLLAR' instead 'USDOLLAR', then the columns will be sorted correctly.
