### ISSUE TITLE
cvxportfolio upgrade for cvxpy version 1.0.3

### ISSUE THREAD

**Issue by sunilshah** [cvxgrp/cvxportfolio#11] opened 2018-05-31 20:21 UTC
cvxportfolio code needs to be upgraded for cvxpy 1.0.3 (current default in PyPi).   Current examples and notebook fail as expected.    Any plans to upgrade and test?

**Comment by mladendalto** [comment] 2018-06-06 06:51
I second @sunilshah 's request.
For me HalloWorld.ipynb crashes at 
sum_entries and mul_elemwise, 
which do not exist in new cvxpy.

**Comment by enzobusseti** [comment] 2018-06-20 19:52
Yes, thanks for noting this. I'll move to 1.0 asap.

**Comment by weiyialanchen** [comment] 2018-06-27 20:16
This can be closed.

**Comment by sunilshah** [comment] 2018-06-27 22:52
Thanks!

The upgraded version fails on two items in my tests.  

1) MultiPeriodOptimization.ipynb



           #            tau = t + delta_t
line no 353 --->            z = cvx.Variable(*w.size)
            wplus = w + z

changing it to 

           z=cvx.Variables(*w.shape)

fixes it on my system (homebrew, mac os, python3, all latest versions).   That makes sense, given the changes in cvxpy. 

2) All tests fail when cvxportfolio is installed using 

pip3 install -U cvxporfolio.
nosetests cvxporfolio. 

I am using homebrew  package manager, rather than conda to install non-python software not maintained by conda on Mac OS.  

 I  clone the repository and run the cloned version of the software rather than the one installed using pip3.  The cloned version runs nosetests fine in the test directory.

**Comment by weiyialanchen** [comment] 2018-06-29 01:00
Perhaps submit a pull request to @enzobusseti regarding item 1?

Regarding item 2, I think tests on the pip installed lib is expected due to missing data (I may misunderstand). It was failing even before.

**Comment by weiyialanchen** [comment] 2018-06-29 01:07
@enzobusseti thanks for taking my pull request first. 

But there might be some potential problems with this upgrade (not captured by the tests), I use your lib for portfolio optimization in actual investment, and recently realized the solver outputs differently (single period optimization policy). From my result speaking, older version works correctly while upgraded version must have something wrong.

I haven't dig into details yet, it might be caused by `cvxpy` rather than `cvxportfolio`, just a note here.

**Comment by sunilshah** [comment] 2018-06-29 02:21
@weiyialanchen 

New definition of leverage could be a reason for the difference.  cvxpy 1.0.x uses OSQP as the default QP solver while cvxpy 0.4.11 used ECOS.  In my tests comparing OSQP with ECOS, I have found OSQP to be more robust, though when both solvers worked, the results were identical within tolerances.

**Comment by enzobusseti** [comment] 2018-07-02 18:46
@sunilshah regarding the test failing, I found an error in the pip package (I wasn't including the test data), which is fixed now. The error only affects the test, not the rest of the library.

@weiyialanchen I changed the definition of leverage (there was a subtle mismatch with the definition in the paper). It shouldn't have big effects, but you might get slightly different numerical results if your strategy uses the leverage limit.

Solvers: OSQP is a new but very good solver, and should have noticeably faster convergence than ECOS. I'm planning to make the default `TCostModel` quadratic (instead of 3/2 power) so that it compiles to a quadratic program and is solved by OSQP.

**Comment by sunilshah** [comment] 2018-07-02 19:03
@enzobusseti 

Thanks for fixing tests.  

As for changing to OSQP as a default, please wait till issue #535 in cvxpy for  OSQP is resolved (or you can use the workaround of changing maximization to minimization).

**Comment by weiyialanchen** [comment] 2018-07-02 20:01
@enzobusseti @sunilshah 

I didn't use a leverage limit. But after changing to ECOS I got my expected output back, thank you guys!!

**Comment by optwave** [comment] 2018-08-04 19:14
@weiyialanchen 

> and recently realized the solver outputs differently (single period optimization policy)

It seems that the outputs of the first experiment with the coarse grid are different from the paper for both SinglePeriodOpt (worse in some cases) and MultiPeriodOpt (better in some cases). AFAICS, I use the latest versions of cxvportfolio and cvxpy. Please find below the corresponding figures. 

SinglePeriodOpt for "2012-01-01"-"2016-12-31" (note that the scaling for y-axis is different from the one paper where max(y-axis) was 30%):
![spo_riskrewardfrontier_5y](https://user-images.githubusercontent.com/24443694/43678255-72b1a9d6-9810-11e8-8485-089d5c1d6dd1.png)

MultiPeriodOpt for "2012-01-01"-"2016-12-31":
![mpo2_riskrewardfrontier_5y](https://user-images.githubusercontent.com/24443694/43678180-a7c28228-980e-11e8-8381-0e42ac563db8.png)


BTW, in MultiPeriodOptimization.ipynb I actually use 
`353  z = cvx.Variable(w.size) `
and not 
`353 z = cvx.Variables(*w.shape)`
as suggested by @sunilshah. The latter caused 
`AttributeError: module 'cvxpy' has no attribute 'Variables'`

I am not sure what the differences are due. It would make sense to benchmark the results under both versions of cvxpy and different versions of cvxportfolio and preferably by a person who understands the internals (I am not the result person in this sense).

Assuming that the results that I get from MultiPeriodOpt are correct, it appears that the results for 10% risk are now ~35% and not ~23% as in Figure 7.5 of the paper, it would be nice to fully understand the origins of this non-trivial difference.

**Comment by bstellato** [comment] 2018-08-07 15:47
@sunilshah looks like the cvxpy issue is now resolved https://github.com/cvxgrp/cvxpy/issues/535

**Comment by sunilshah** [comment] 2018-08-13 23:42
@bstellato 

Yes, it appears to be fixed.  However, I have not personally verified it.

@optwave 

Thanks for point out my typo, which is fixed in my comment now.

 @enzobusseti 

It may be worth testing out OSQP as the default solver now.

**Comment by enzobusseti** [comment] 2018-08-14 03:44
@optwave , thanks for reporting. it might also be related to #14 (there was a bug in the definition of leverage limit, it makes sense if the results changed a bit). 

If there is a $3/2$ transaction cost model the problem should compile to SOCP and default to ECOS. To force OSQP you can pass `solver = 'OSQP'` to the SPO policy object (but that will raise an exception if you use the $3/2$ tcost). (I believe OSQP is preferable, but it's up to the user.)

`cvx.Variables` is a typo, feel free to make a pull request..

**Comment by quant9** [comment] 2023-05-24 15:27
@enzbus can this old issue be closed? https://github.com/cvxgrp/cvxportfolio/blob/master/setup.py#L21

**Closed** 2023-09-12 08:07 UTC
